# Use the base image with specified platform
FROM aelf/node:testnet-release-v1.12.2

# Copy the fireaelf file from the second image with specified platform
COPY --from=ghcr.io/gldeng/firehose-aelf:edbade0 /app/fireaelf /app

COPY --from=gldeng/aelf-test-node:sha72ef2bd /app/AElf.Launcher.* /app
COPY --from=gldeng/aelf-test-node:sha72ef2bd /app/AElf.Firehose.* /app

# Set the entrypoint to /app/fireaelf
ENTRYPOINT ["/app/fireaelf"]
